apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "openrtist.name" . }}
    chart: {{ template "openrtist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "openrtist.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: port
      port: {{ .Values.service.port }}
{{ if eq .Values.service.type "NodePort"}}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
{{ end }}
