# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openrtist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openrtist.proto',
  package='openrtist',
  syntax='proto3',
  serialized_options=_b('\n\024edu.cmu.cs.openrtistB\006Protos'),
  serialized_pb=_b('\n\x0fopenrtist.proto\x12\topenrtist\"\x99\x02\n\x06\x45xtras\x12\r\n\x05style\x18\x01 \x01(\t\x12\x34\n\nstyle_list\x18\x02 \x03(\x0b\x32 .openrtist.Extras.StyleListEntry\x12\x31\n\x0bstyle_image\x18\x03 \x01(\x0b\x32\x1c.openrtist.Extras.BytesValue\x12\x17\n\x0f\x64\x65pth_threshold\x18\x04 \x01(\x05\x12/\n\tdepth_map\x18\x05 \x01(\x0b\x32\x1c.openrtist.Extras.BytesValue\x1a\x1b\n\nBytesValue\x12\r\n\x05value\x18\x01 \x01(\x0c\x1a\x30\n\x0eStyleListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1e\n\x14\x65\x64u.cmu.cs.openrtistB\x06Protosb\x06proto3')
)




_EXTRAS_BYTESVALUE = _descriptor.Descriptor(
  name='BytesValue',
  full_name='openrtist.Extras.BytesValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='openrtist.Extras.BytesValue.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=262,
)

_EXTRAS_STYLELISTENTRY = _descriptor.Descriptor(
  name='StyleListEntry',
  full_name='openrtist.Extras.StyleListEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='openrtist.Extras.StyleListEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='openrtist.Extras.StyleListEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=312,
)

_EXTRAS = _descriptor.Descriptor(
  name='Extras',
  full_name='openrtist.Extras',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='style', full_name='openrtist.Extras.style', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='style_list', full_name='openrtist.Extras.style_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='style_image', full_name='openrtist.Extras.style_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_threshold', full_name='openrtist.Extras.depth_threshold', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_map', full_name='openrtist.Extras.depth_map', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EXTRAS_BYTESVALUE, _EXTRAS_STYLELISTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=312,
)

_EXTRAS_BYTESVALUE.containing_type = _EXTRAS
_EXTRAS_STYLELISTENTRY.containing_type = _EXTRAS
_EXTRAS.fields_by_name['style_list'].message_type = _EXTRAS_STYLELISTENTRY
_EXTRAS.fields_by_name['style_image'].message_type = _EXTRAS_BYTESVALUE
_EXTRAS.fields_by_name['depth_map'].message_type = _EXTRAS_BYTESVALUE
DESCRIPTOR.message_types_by_name['Extras'] = _EXTRAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Extras = _reflection.GeneratedProtocolMessageType('Extras', (_message.Message,), dict(

  BytesValue = _reflection.GeneratedProtocolMessageType('BytesValue', (_message.Message,), dict(
    DESCRIPTOR = _EXTRAS_BYTESVALUE,
    __module__ = 'openrtist_pb2'
    # @@protoc_insertion_point(class_scope:openrtist.Extras.BytesValue)
    ))
  ,

  StyleListEntry = _reflection.GeneratedProtocolMessageType('StyleListEntry', (_message.Message,), dict(
    DESCRIPTOR = _EXTRAS_STYLELISTENTRY,
    __module__ = 'openrtist_pb2'
    # @@protoc_insertion_point(class_scope:openrtist.Extras.StyleListEntry)
    ))
  ,
  DESCRIPTOR = _EXTRAS,
  __module__ = 'openrtist_pb2'
  # @@protoc_insertion_point(class_scope:openrtist.Extras)
  ))
_sym_db.RegisterMessage(Extras)
_sym_db.RegisterMessage(Extras.BytesValue)
_sym_db.RegisterMessage(Extras.StyleListEntry)


DESCRIPTOR._options = None
_EXTRAS_STYLELISTENTRY._options = None
# @@protoc_insertion_point(module_scope)
