# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openrtist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openrtist.proto',
  package='openrtist',
  syntax='proto3',
  serialized_pb=_b('\n\x0fopenrtist.proto\x12\topenrtist\"\x1d\n\x0c\x45ngineFields\x12\r\n\x05style\x18\x01 \x01(\tB\x1e\n\x14\x65\x64u.cmu.cs.openrtistB\x06Protosb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENGINEFIELDS = _descriptor.Descriptor(
  name='EngineFields',
  full_name='openrtist.EngineFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='style', full_name='openrtist.EngineFields.style', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['EngineFields'] = _ENGINEFIELDS

EngineFields = _reflection.GeneratedProtocolMessageType('EngineFields', (_message.Message,), dict(
  DESCRIPTOR = _ENGINEFIELDS,
  __module__ = 'openrtist_pb2'
  # @@protoc_insertion_point(class_scope:openrtist.EngineFields)
  ))
_sym_db.RegisterMessage(EngineFields)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024edu.cmu.cs.openrtistB\006Protos'))
# @@protoc_insertion_point(module_scope)
