# Default values for openrtist service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 1
  port: 9099
  protocol: TCP
  gpu: true

image:
  repository: cmusatyalab/openrtist
  tag: stable
  pullPolicy: IfNotPresent

service:
  name: openrtist-svc
  type: NodePort
  port: 9099
  targetPort: 9099
