# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openrtist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fopenrtist.proto\x12\topenrtist\"\x99\x02\n\x06\x45xtras\x12\r\n\x05style\x18\x01 \x01(\t\x12\x34\n\nstyle_list\x18\x02 \x03(\x0b\x32 .openrtist.Extras.StyleListEntry\x12\x31\n\x0bstyle_image\x18\x03 \x01(\x0b\x32\x1c.openrtist.Extras.BytesValue\x12\x17\n\x0f\x64\x65pth_threshold\x18\x04 \x01(\x05\x12/\n\tdepth_map\x18\x05 \x01(\x0b\x32\x1c.openrtist.Extras.BytesValue\x1a\x1b\n\nBytesValue\x12\r\n\x05value\x18\x01 \x01(\x0c\x1a\x30\n\x0eStyleListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1e\n\x14\x65\x64u.cmu.cs.openrtistB\x06Protosb\x06proto3')



_EXTRAS = DESCRIPTOR.message_types_by_name['Extras']
_EXTRAS_BYTESVALUE = _EXTRAS.nested_types_by_name['BytesValue']
_EXTRAS_STYLELISTENTRY = _EXTRAS.nested_types_by_name['StyleListEntry']
Extras = _reflection.GeneratedProtocolMessageType('Extras', (_message.Message,), {

  'BytesValue' : _reflection.GeneratedProtocolMessageType('BytesValue', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_BYTESVALUE,
    '__module__' : 'openrtist_pb2'
    # @@protoc_insertion_point(class_scope:openrtist.Extras.BytesValue)
    })
  ,

  'StyleListEntry' : _reflection.GeneratedProtocolMessageType('StyleListEntry', (_message.Message,), {
    'DESCRIPTOR' : _EXTRAS_STYLELISTENTRY,
    '__module__' : 'openrtist_pb2'
    # @@protoc_insertion_point(class_scope:openrtist.Extras.StyleListEntry)
    })
  ,
  'DESCRIPTOR' : _EXTRAS,
  '__module__' : 'openrtist_pb2'
  # @@protoc_insertion_point(class_scope:openrtist.Extras)
  })
_sym_db.RegisterMessage(Extras)
_sym_db.RegisterMessage(Extras.BytesValue)
_sym_db.RegisterMessage(Extras.StyleListEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024edu.cmu.cs.openrtistB\006Protos'
  _EXTRAS_STYLELISTENTRY._options = None
  _EXTRAS_STYLELISTENTRY._serialized_options = b'8\001'
  _EXTRAS._serialized_start=31
  _EXTRAS._serialized_end=312
  _EXTRAS_BYTESVALUE._serialized_start=235
  _EXTRAS_BYTESVALUE._serialized_end=262
  _EXTRAS_STYLELISTENTRY._serialized_start=264
  _EXTRAS_STYLELISTENTRY._serialized_end=312
# @@protoc_insertion_point(module_scope)
